# Generated by Django 3.1.7 on 2021-03-31 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('em', '0007_auto_20210331_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='accout',
            new_name='account',
        ),
    ]
