# Generated by Django 3.1.7 on 2021-03-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em', '0008_auto_20210331_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
