# Generated by Django 3.1.7 on 2021-04-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em', '0011_account_statement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='statement_date',
            field=models.IntegerField(default=1, help_text='Statement Date'),
        ),
    ]
