# Generated by Django 3.1.7 on 2021-04-14 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('em', '0012_auto_20210414_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='statement_date',
        ),
    ]
