# Generated by Django 3.1.7 on 2021-04-28 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('em', '0014_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='em.account'),
        ),
    ]
