# Generated by Django 3.1.7 on 2021-03-22 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(blank=True, default='#2E64FE', max_length=20, null=True)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('desc', models.TextField(blank=True, null=True)),
                ('tran_type', models.CharField(choices=[('EX', 'Expense'), ('IN', 'Income')], default='EX', max_length=2)),
                ('title', models.CharField(max_length=200, unique_for_date='date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='em.category')),
            ],
        ),
    ]
