# Generated by Django 3.1.7 on 2021-03-22 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('em', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='modified_date',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='modified_date',
            new_name='updated_at',
        ),
    ]
