# Generated by Django 3.1.7 on 2021-03-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em', '0005_auto_20210323_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=200, unique=True)),
                ('value', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
